<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/06/01 00:14:00
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 10,
));
