<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/05/31 23:56:23
$this->security = array (
  'index' => 
  array (
    'is_secure' => 'off',
  ),
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 'admin',
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
);
