<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/06/01 16:49:41
$this->security = array (
  'index' => 
  array (
    'is_secure' => 'off',
  ),
  'all' => 
  array (
    'is_secure' => 'on',
    'credentials' => 'admin',
  ),
);
